[
    {
        "id": "app.error.reportErrorTitle",
        "description": "title for report error modal",
        "defaultMessage": "エラーを報告"
    },
    {
        "id": "app.error.thankYouForYourFeedback",
        "description": "thank you for feedback",
        "defaultMessage": "フィードバックありがとうございます！"
    },
    {
        "id": "app.error.copyTheFollowingLines",
        "description": "text explaining what to do to report an issue on GH",
        "defaultMessage": "次のラインをコピーして {githubLink} に新しい議論すべき話題を作成してください"
    },
    {
        "id": "app.error.alsoCheckForOpenedIssues",
        "description": "text suggesting to check for existing issues",
        "defaultMessage": "Also check if there are no already opened issues regarding this error!"
    },
    {
        "id": "app.error.backupKeys",
        "description": "error message for backup keys action",
        "defaultMessage": "バックアップの生成に失敗しました。もう一度やり直してください"
    },
    {
        "id": "app.error.commentsDownvote",
        "description": "error message for downvoting a comment",
        "defaultMessage": "An error occurred while downvoting a comment"
    },
    {
        "id": "app.error.commentsPublish",
        "description": "error message for publishing a comment",
        "defaultMessage": "コメントを公開中にエラーが発生しました"
    },
    {
        "id": "app.error.commentsUpvote",
        "description": "error message for upvoting a comment",
        "defaultMessage": "An error occurred while upvoting a comment"
    },
    {
        "id": "app.error.dashboardAdd",
        "description": "error message for creating a new board",
        "defaultMessage": "新しいボードの保存中にエラーが発生しました"
    },
    {
        "id": "app.error.dashboardAddColumn",
        "description": "error message for adding a column to a board",
        "defaultMessage": "新しいコラムを保存中にエラーが発生しました"
    },
    {
        "id": "app.error.dashboardDelete",
        "description": "error message for deleting a board",
        "defaultMessage": "あなたの掲示板を削除中にエラーが発生しました"
    },
    {
        "id": "app.error.dashboardDeleteColumn",
        "description": "error message for removing a column from a board",
        "defaultMessage": "あなたのコラムを削除中にエラーが発生しました"
    },
    {
        "id": "app.error.dashboardGetActive",
        "description": "error message for fetching the active board",
        "defaultMessage": "アクティブボードを取得中にエラーが発生しました"
    },
    {
        "id": "app.error.dashboardGetAll",
        "description": "error message for fetching all boards",
        "defaultMessage": "あなたの掲示板を取得中にエラーが発生しました"
    },
    {
        "id": "app.error.dashboardSetActive",
        "description": "error message for setting the active board",
        "defaultMessage": "あなたのアクティブボードの保存中にエラーが発生しました"
    },
    {
        "id": "app.error.dashboardUpdateColumn",
        "description": "error message for updating a column",
        "defaultMessage": "あなたのコラムを更新中にエラーが発生しました"
    },
    {
        "id": "app.error.draftAutosave",
        "description": "error message for autosaving a draft",
        "defaultMessage": "このドラフトの最新の変更を保存できません"
    },
    {
        "id": "app.error.draftPublish",
        "description": "error message for publishing a draft",
        "defaultMessage": "下書きを公開中にエラーが発生しました"
    },
    {
        "id": "app.error.entriesGetAsDrafts",
        "description": "error message for fetching your own entries",
        "defaultMessage": "あなたの投稿を取得中にエラーが発生しました。ローカルの下書きのみが表示されています"
    },
    {
        "id": "app.error.entryClaim",
        "description": "error message for collecting Essence for an entry",
        "defaultMessage": "An error occurred while collecting Essence for {entryTitle}"
    },
    {
        "id": "app.error.entryClaimVote",
        "description": "error message for collecting Essence for a vote",
        "defaultMessage": "An error occurred while collecting Essence for {entryTitle}"
    },
    {
        "id": "app.error.entryDownvote",
        "description": "error message for downvoting an entry",
        "defaultMessage": "{entryTitle} にDownvoting中にエラーが発生しました"
    },
    {
        "id": "app.error.entryGetFull",
        "description": "error message for fetching a full entry",
        "defaultMessage": "投稿のデータを取得中にエラーが発生しました"
    },
    {
        "id": "app.error.entryListIterator",
        "description": "error message for fetching entries in a list",
        "defaultMessage": "リスト内の投稿を取得中にエラーが発生しました"
    },
    {
        "id": "app.error.entryUpvote",
        "description": "error message for upvoting an entry",
        "defaultMessage": "{entryTitle} にUpvoting中にエラーが発生しました"
    },
    {
        "id": "app.error.errorNotificationTitle",
        "description": "title for error notifcations",
        "defaultMessage": "エラーコード {errorCode}"
    },
    {
        "id": "app.error.fatalError",
        "description": "title for fatal error modal",
        "defaultMessage": "フェイタルエラー"
    },
    {
        "id": "app.error.generalSettings",
        "description": "error message for fetching general settings",
        "defaultMessage": "全般設定を取得中にエラーが発生しました"
    },
    {
        "id": "app.error.gethGetOptions",
        "description": "error message for fetching geth options",
        "defaultMessage": "Geth serviceオプションを取得中にエラーが発生しました"
    },
    {
        "id": "app.error.gethGetStatus",
        "description": "error message for fetching geth status",
        "defaultMessage": "Geth serviceステータスを取得中にエラーが発生しました"
    },
    {
        "id": "app.error.gethGetSyncStatus",
        "description": "error message for fetching geth synchronization status",
        "defaultMessage": "同期ステータスを取得中にエラーが発生しました"
    },
    {
        "id": "app.error.gethSaveSettings",
        "description": "error message for saving geth settings",
        "defaultMessage": "An error occurred while saving your geth settings"
    },
    {
        "id": "app.error.gethSettings",
        "description": "error message for fetching geth settings",
        "defaultMessage": "An error occurred while getting your geth settings"
    },
    {
        "id": "app.error.gethStart",
        "description": "error message for starting geth service",
        "defaultMessage": "Geth service could not be started"
    },
    {
        "id": "app.error.gethStop",
        "description": "error message for stopping geth service",
        "defaultMessage": "Geth service could not be stopped"
    },
    {
        "id": "app.error.ipfsGetConfig",
        "description": "error message for fetching IPFS service configuration",
        "defaultMessage": "An error occurred while getting IPFS service config"
    },
    {
        "id": "app.error.ipfsGetPorts",
        "description": "error message for fetching IPFS ports",
        "defaultMessage": "An error occurred while getting IPFS service ports"
    },
    {
        "id": "app.error.ipfsSaveSettings",
        "description": "error message for saving IPFS settings",
        "defaultMessage": "An error occurred while saving your IPFS settings"
    },
    {
        "id": "app.error.ipfsSetPorts",
        "description": "ipfs set ports error message",
        "defaultMessage": "An error occurred while setting ipfs service ports"
    },
    {
        "id": "app.error.ipfsSettings",
        "description": "error message for fetching IPFS settings",
        "defaultMessage": "An error occurred while getting your IPFS settings"
    },
    {
        "id": "app.error.ipfsStart",
        "description": "error message for starting IPFS service",
        "defaultMessage": "IPFS service could not be started"
    },
    {
        "id": "app.error.ipfsGetStatus",
        "description": "error message for fetching IPFS service status",
        "defaultMessage": "An error occurred while getting IPFS service status"
    },
    {
        "id": "app.error.ipfsStop",
        "description": "error message for stopping IPFS service",
        "defaultMessage": "IPFS service could not be stopped"
    },
    {
        "id": "app.error.unexpectedError",
        "description": "a general error (with no error code)",
        "defaultMessage": "Unexpected error"
    },
    {
        "id": "app.error.profileBondAeth",
        "description": "error message for bonding (manafying) AETH",
        "defaultMessage": "An error occured while manafying {amount} AETH"
    },
    {
        "id": "app.error.profileCycleAeth",
        "description": "error message for cycling AETH",
        "defaultMessage": "An error occured while cycling {amount} AETH"
    },
    {
        "id": "app.error.profileFreeAeth",
        "description": "error message for freeing AETH that was cycled",
        "defaultMessage": "An error occured while collecting your cycled AETH"
    },
    {
        "id": "app.error.profileGetLocal",
        "description": "error message for fetching local profiles",
        "defaultMessage": "An error occured while fetching local profiles"
    },
    {
        "id": "app.error.profileGetList",
        "description": "error message for fetching a list of profiles",
        "defaultMessage": "An error occured while getting the list of profiles"
    },
    {
        "id": "app.error.profileToggleDonations",
        "description": "error message for changing the settings for accepting tips",
        "defaultMessage": "An error occured while changing your tips settings"
    },
    {
        "id": "app.error.profileTransferAeth",
        "description": "error message for transferring AETH",
        "defaultMessage": "An error occured while transferring {tokenAmount} AETH"
    },
    {
        "id": "app.error.profileTransferEth",
        "description": "error message for transferring ETH",
        "defaultMessage": "An error occured while transferring {value} ETH"
    },
    {
        "id": "app.error.profileTransformEssence",
        "description": "error message for transforming Essence in AETH",
        "defaultMessage": "An error occured while transforming {amount} Essence"
    },
    {
        "id": "app.error.profileUpdate",
        "description": "error message for updating your profile",
        "defaultMessage": "An error occured while updating your profile"
    },
    {
        "id": "app.error.saveGeneralSettings",
        "description": "error message for saving general settings",
        "defaultMessage": "An error occurred while saving your settings"
    }
]